name = "Project Titan"
author = "lind3r"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42c71b5e1c6e0579779c20ffb0a24e5d8f15e6a6c9a0074a2836744f3e7e726c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
