name = "Project Titan"
author = "lind3r"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f53eb79e6b2fb41d9fdf9d705f74eb38c7e3f9f22391fbcfe97474912dd14db6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
