name = "Project Titan"
author = "lind3r"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "620ff7a6b18b4f1ee30e3e9a6cd15af5156975f5994a30d6b85d2a4500a8bd72"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
